apiVersion: v1
kind: PersistentVolume
metadata:
  name: fossology-repo-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  hostPath:
    path: /tmp/fossology-repo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fossology-repo
  namespace: fossology
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  resources:
    requests:
      storage: 10Gi
  volumeName: fossology-repo-pv
