apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fossology.dbSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fossology.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.fossology.db.name | quote }}
  POSTGRES_USER: {{ .Values.fossology.db.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.fossology.db.password | quote }}
