apiVersion: v1
kind: Service
metadata:
  name: {{ include "fossology.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fossology.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    {{- include "fossology.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - port: 80
      targetPort: 80
      name: http
